### ISSUE TITLE
Usage questions / best practices.

### ISSUE THREAD

**Issue by cmackenziek** [proofit404/mappers#255]
Hi ! If this is not the right place to post something like this, please feel free to delete.

I'm looking into using this library in order to implement a cleaner architecture for a web app. The web app is basically a financial data dashboard, most views are calculations over historical data.

I'm currently a big user of Django model annotations (though I'm starting to regret it now that I realize there is a bunch of business logic running in my queries). **How do you reason about model annotations and table joins in general at the domain entities layer?** If there are for example three different queries on the same model, with three different sets of annotations, is it a more common practice to think about these as different entities altogether or to design a more complex domain entity that accomodates the three use cases?

Last question: 
Many of my queries rely on calling `.values("value_1", "value_2")` for filtering. **Does the library currently support mapping from querysets with a `.values()` call?** I haven't seen any examples and couldn't figure it out by looking at the code.

Any pointers regarding these questions would be immensely appreciated and really help our team adopt the library. Thanks !!

I love the idea of this library and dry-python in general ! Please let me know if you need more hands for development of these libraries.

**Comment by proofit404** [comment]
Hi, thank you for your patience. Usually, I answer during working hours Moscow time. I prefer to be away from the PS during weekends.

1. Usually, I prefer to keep different data inside the class related to the domain. For example, if we have tables like `User`, `Delivery`, `Parcel`, `Order`, and `Shipment` it'll result in one entity class `Shopping` with some fields from `User` table, some fields from `Delivery` table, etc. All the fields should be used in methods defined in this `Shopping` class. All the joins, annotations, and aggregate functions should be hidden from the `Shopping` class behind the reader functions.

2. `mappers` use `values_list` method under the hood when we read entities from querysets. From what I understand chaining `values` with `values_list` in Django should not be a problem.

If it causes any problems, let me know. It should be fixed.

All contributions would be highly appreciated! If you want to contribute to the libraries, let's discuss the goal in the issues and work on the PR after the goal was set.

Have a good day :tada: 

Best regards,
Artem.

**Comment by cmackenziek** [comment]
Thanks! I'll give the library a try and come back with any comments if I have problems or suggestions.
