### ISSUE TITLE
Take note of Odin

### ISSUE THREAD

**Issue by thedrow** [proofit404/mappers#47]
[`Odin`](https://github.com/python-odin/odin/) is a library which provided this functionality for a very long time.
Odin didn't use data classes as they were not available at that time unfortunately.

It's worth learning the approach it took and it's design to see if there's something to improve in this library.

BTW, I really needed this.

**Comment by proofit404** [comment]
Hi,

Thanks for the info! I didn't know about it.

Regards,
Artem.

**Comment by sobolevn** [comment]
> BTW, I really needed this.

**Comment by thedrow** [comment]
A mapper that supports dataclasses instead of custom classes.

**Comment by proofit404** [comment]
We have no plans to support Odin's resources. Only attrs, dataclasses, and pydantic will be supported.
